jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        uses: srvaroa/labeler@master
name: "Label PRs"
on: [pull_request]
